# Generated by Django 6.1 on 2026-08-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('severidad', models.CharField(max_length=20)),
                ('asunto', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=40)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(null=True)),
            ],
        ),
    ]
