# Generated by Django 6.1 on 2026-08-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eluviatechapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
